apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: httpserver
  name: httpserver
spec:
  replicas: 2
  selector:
    matchLabels:
      run: httpserver
  template:
    metadata:
      labels:
        run: httpserver
    spec:
      containers:
        - image: drinkey/httpserver
          name: httpserver
          envFrom:
          - configMapRef:
              name: httpserver-env-prod
          volumeMounts:
          - name: httpserver-prod-ini
            mountPath: "/etc/httpserver"
            readOnly: true
      volumes:
      - name: httpserver-prod-ini
        configMap:
          name: httpserver-config