apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpserver
  name: httpserver
spec:
  type: NodePort
  ports:
  - nodePort: 31317
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    run: httpserver